alefragnani.project-manager
antfu.iconify
astro-build.astro-vscode
augment.vscode-augment
bradlc.vscode-tailwindcss
catppuccin.catppuccin-vsc-icons
dbaeumer.vscode-eslint
dnicolson.binary-plist
docker.docker
eamodio.gitlens
enkia.tokyo-night
esbenp.prettier-vscode
formulahendry.auto-close-tag
formulahendry.auto-complete-tag
formulahendry.auto-rename-tag
github.copilot
github.copilot-chat
github.vscode-github-actions
github.vscode-pull-request-github
golang.go
gruntfuggly.todo-tree
johnsoncodehk.vscode-tsconfig-helper
josemurilloc.aura-spirit-dracula
kisstkondoros.vscode-gutter-preview
laravel.vscode-laravel
liamhammett.inline-parameters
lzm0x219.vscode-markdown-github
meganrogge.template-string-converter
mhutchie.git-graph
ms-azuretools.vscode-containers
ms-azuretools.vscode-docker
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode.makefile-tools
ms-vscode.remote-explorer
naumovs.color-highlight
nuxtr.nuxtr-vscode
patbenatar.advanced-new-file
pkief.material-icon-theme
qwtel.sqlite-viewer
rangav.vscode-thunder-client
rodrigovallades.es7-react-js-snippets
sanjulaganepola.github-local-actions
sdras.vue-vscode-snippets
sheltonlouis.astro-snippets
streetsidesoftware.code-spell-checker
subframe7536.custom-ui-style
unifiedjs.vscode-mdx
usernamehw.errorlens
vitest.explorer
vue.volar
vunguyentuan.vscode-css-variables
yoavbls.pretty-ts-errors
