import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
# family = "MesloLGS Nerd Font Mono"
family = "CaskaydiaCove Nerd Font"
style = "Bold"


[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"


[terminal.shell]
program = "/usr/bin/fish"
