name: Generate Changelog

on:
  workflow_call:
jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Generate changelog
        uses: actions/github-script@v6
        with:
          script: |
            const {generateChangelog} = require('./github/workflow-scripts/generateChangelog')
            const version = '${{ github.ref_name}}'
            await generateChangelog(version, '${{ github.token}}')
